### ISSUE TITLE
Please make this plugin compatible with IntelliJ IDEA 2018.3

### ISSUE THREAD

**Issue by ofry** [jozic/quick-patch#13]
```
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019

JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
KUbuntu 18.10 64-bit
```

Quick Patch v0.0.4

"Settings->Quick Patch" entry doesn't exist.

**Comment by jozic** [comment]
thanks for the issue!
since git arrived I don't use the plugin myself, as branching is so easy with it, and I used to use the plugin a lot while working with svn
but anyway, i will see what i can do soon

**Comment by jozic** [comment]
@ofry updated code and uploaded new version of plugin (0.1.0) that is compatible with intellij 2018.1-2018.3

Please give it a try and let me know if it works for you. 
Feel free to reopen or create new issues if something doesn't work
